-- MySQL Script generated by MySQL Workbench
-- Tue Nov 27 12:52:42 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kanfan
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kanfan
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kanfan` DEFAULT CHARACTER SET utf8 ;
USE `kanfan` ;

-- -----------------------------------------------------
-- Table `kanfan`.`auth_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kanfan`.`auth_user` ;

CREATE TABLE IF NOT EXISTS `kanfan`.`auth_user` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kanfan`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kanfan`.`account` ;

CREATE TABLE IF NOT EXISTS `kanfan`.`account` (
  `id` INT NOT NULL,
  `auth_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_account_auth_user1_idx` (`auth_user_id` ASC),
  CONSTRAINT `fk_account_auth_user1`
    FOREIGN KEY (`auth_user_id`)
    REFERENCES `kanfan`.`auth_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kanfan`.`bangumi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kanfan`.`bangumi` ;

CREATE TABLE IF NOT EXISTS `kanfan`.`bangumi` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `rss` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `creator` INT NOT NULL,
  `season` VARCHAR(45) NULL,
  `year` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bangumi_account1_idx` (`creator` ASC),
  CONSTRAINT `fk_bangumi_account1`
    FOREIGN KEY (`creator`)
    REFERENCES `kanfan`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kanfan`.`episode`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kanfan`.`episode` ;

CREATE TABLE IF NOT EXISTS `kanfan`.`episode` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `file` VARCHAR(45) NULL,
  `torrent` VARCHAR(45) NULL,
  `magnet` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `bangumi_id` INT NOT NULL,
  `subtitle_file` VARCHAR(45) NULL,
  `subtitle_torrent` VARCHAR(45) NULL,
  `subtitle_magnet` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_episode_bangumi_idx` (`bangumi_id` ASC),
  CONSTRAINT `fk_episode_bangumi`
    FOREIGN KEY (`bangumi_id`)
    REFERENCES `kanfan`.`bangumi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kanfan`.`follow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kanfan`.`follow` ;

CREATE TABLE IF NOT EXISTS `kanfan`.`follow` (
  `id` INT NOT NULL,
  `account_id` INT NOT NULL,
  `bangumi_id` INT NOT NULL,
  `state` VARCHAR(45) NULL,
  `last_episode_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_follow_account1_idx` (`account_id` ASC),
  INDEX `fk_follow_bangumi1_idx` (`bangumi_id` ASC),
  INDEX `fk_follow_episode1_idx` (`last_episode_id` ASC),
  CONSTRAINT `fk_follow_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `kanfan`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_follow_bangumi1`
    FOREIGN KEY (`bangumi_id`)
    REFERENCES `kanfan`.`bangumi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_follow_episode1`
    FOREIGN KEY (`last_episode_id`)
    REFERENCES `kanfan`.`episode` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
